### ISSUE TITLE
When started, nothing comes up at 192.168.0.100:8080

### ISSUE THREAD

**Issue by calgara12** [EmmaRamirez/nuzlocke-generator#129]
Hey. I wanted to try this application, and i tried to run it on my ubuntu server, as it is documented in the ReadMe. But once i start it and open 192.168.0.100:8080 i get the message This site can’t be reached.

However when i try to install it locally on windows and run it, it works. On windows i have npm version 6.4.1. On Ubuntu i have 6.7.0

EDIT: Here is the output i get when i execute the ´npm run serve´:
https://pastebin.com/CKEuZEMN

Maybe you are able to help me :)
Thank you in advance

**Comment by calgara12** [comment]
I fixed this by editing the options.js file inside node_modules/webpack-serve/lib

i just changed localhost to 0.0.0.0 

Now it its accessible with my local ip.

**Comment by EmmaRamirez** [comment]
Sorry I hadn't seen this, I'm glad you found a fix!
