### ISSUE TITLE
Doesn't save my progress

### ISSUE THREAD

**Issue by JkHowling** [EmmaRamirez/nuzlocke-generator#132]
Literally half the time, whenever I use this app, it resets itself for literally 0 reason whatsoever. I've lost hours of progress on a run because the stupid thing just completely ignores everything I've input into it for the past 5 hours and resets to what it was earlier.

Yes, I click Save. I click Force Save. I clicked both of them about a dozen times yesterday. Still lost all my progress. Might go back to using google sheets at this point. 

Edit: One thing I noticed is that it happens most often when using the import data function.. every time I import data, I have to do it twice, or else it doesn't save and reverts back to what was on it before I imported. Even if I press save or force save.

**Comment by EmmaRamirez** [comment]
If you could paste in your `nuzlocke.json` and then the browser & OS versions you are using, I can take a look at it. I would imagine there's possibly a bug there with the import data function.

**Comment by EmmaRamirez** [comment]
Sorry for all the trouble you're having with it
