### ISSUE TITLE
Blank Page When I Open

### ISSUE THREAD

**Issue by detypeac1er** [EmmaRamirez/nuzlocke-generator#189]
Every time I try to open the Nuzlocke Generator Webapp, it gives me the Pokeball Loading Screen and then just gives me a white screen. Could you help me fix this?
 
<img width="1435" alt="Screenshot 2020-03-22 at 19 28 55" src="https://user-images.githubusercontent.com/62519432/77258606-78167d00-6c73-11ea-8945-193d020574ba.png">

**Comment by EmmaRamirez** [comment]
Hi there, sorry for the late response. Have you tried clearing your localStorage?

**Comment by detypeac1er** [comment]
Hi, everything is fine it fixed itself. Thanks anyways.
