### ISSUE TITLE
TCG images

### ISSUE THREAD

**Issue by BlazeVolt** [EmmaRamirez/nuzlocke-generator#353]
Hello

I noticed an option for TCG pokemon images in the generator and also that most of the pokemon in the category are missing images. Seeing as its mostly just a time consuming job (find the image, crop, fix it, next) I can help with them.
Here are some samples
http://www.mediafire.com/file/7buks1wrs53arai/tcg.7z/file

**Comment by EmmaRamirez** [comment]
Thank you so much for your contribution! I'll be adding these to the next release of the generator. You're also free to submit a pull request, if that's up your alley.

The option for TCG images should only be available locally and that's simply because it does lack so many Pokémon. Please let me know if you're willing to take up adding more images. Thank you so much!

**Comment by BlazeVolt** [comment]
I am currently done up to Tentacool (with regional forms also done and some later evos, f.e. Crobat). 
Will do some more latter on and submit a pull request then.

**Comment by EmmaRamirez** [comment]
I made some changes to configuring tcg images (will update readme shortly)

In the root of the `nuzlocke-generator` folder, add a file named `.env` & include this:

```
TCG_IMAGES=true
```

This should allow you to select the tcg images dropdown

**Comment by BlazeVolt** [comment]
Deleting the local folders and cloning again, making a new .env and running npm install fixed tcg option not showing up

**Comment by BlazeVolt** [comment]
Done, I think you can close the issue.
List of missing images and which forms are not working:
https://pastebin.com/KX7rKMDJ

All images in one place
https://www.mediafire.com/file/0jvcx63ejdn18y3/TCG_Upload.7z/file

**Comment by EmmaRamirez** [comment]
@BlazeVolt You're right, I'll close this issue out and make a new one for the remaining forms. Thank you so much for your hard work on this, I really appreciate it!!
