### ISSUE TITLE
Autocomplete on species doesn't update image

### ISSUE THREAD

**Issue by MPSonline** [EmmaRamirez/nuzlocke-generator#45]
When using the autocomplete dropdown entering the Pokemon species, clicking the suggested name fills in the field on both the form and output, but does not update the Pokemon's image on the output. Changing the value with keyboard and putting it back to the suggested value by adding/deleting the extra characters correctly updates the image.

Steps to reproduce:

1. Enter enough text in the Pokemon species field to prompt a suggestion
2. Click the suggestion
3. Image does not update in the output

**Comment by EmmaRamirez** [comment]
This should be fixed now, it'll update both when you click one of the list items, or enter Tab or Enter. Thanks for reporting this!
