### ISSUE TITLE
Setting types with mass editor not possible

### ISSUE THREAD

**Issue by fhedor** [EmmaRamirez/nuzlocke-generator#56]
Setting any types with the mass editor will just reset to "Bug Bug", leaving the field blank will set "None None". In both cases setting types with the drop down menu becomes impossible.
Alternatively, the site crashes completely when trying to use mass editor (on Firefox only so far. It reloads but stays blank. Have to clear the cache before I can access it again)

**Comment by EmmaRamirez** [comment]
That's a pretty bad bug. Thanks for reporting it. I think the mass editor needs some work in general, I'll take a look at it

**Comment by EmmaRamirez** [comment]
It's been fixed! Just make sure to use commas, i.e. "Bug, Bug"
