### ISSUE TITLE
Add ability to export nuzlocke templates into an image file

### ISSUE THREAD

**Issue by tehponycorn** [EmmaRamirez/nuzlocke-generator#58]
Currently to share nuzlocke templates one must take a screenshot of the template and edit it in an image-editing software. Adding the ability to export a template as a .jpeg or .png file would allow for one to download their templates easily instead of having to go through multiple steps to share them.

**Comment by EmmaRamirez** [comment]
Hey there! Thanks for the issue submission!

This is now active as of `0.0.7-beta`
